class Cities {
   List<String>  cities = [
    'Ávila', 
    'Amsterdam',
    'ACoruña',
    'Almería',
    'Albacete',
    'Alicante',
    'Algeciras',
    'Arrecife',
    'Bahamas',
    'Barcelona',
    'Bogota',
    'Bilbao',
    'Burgos',
    'Badajoz',
    'Cali',
    'Copenhagen',
    'Cartagena',
    'Cádiz',
    'Castellón de la Plana',
    'Cáceres',
    'Córdoba',
    'Cologne',
    'Ciudad Real',
    'Cuenca',
    'Donostia',
    'Granada',
    'Germany',
    'Gijón',
    'Girona',
    'Guadalajara',
    'Honduras',
    'Haiti',
    'Huesca',
    'Huelva',
    'Jamaica',
    'Jaén',
    'Las Palmas de Gran Canaria',
    'León',
    'Logroño',
    'Lorca',
    'Linares',
    'Lleida',
    'Lugo',
    'Madrid',
    'Marbella',
    'Mataró',
    'New York',
    'Netherlands',
    'Norway',
    'Macao',
    'Málaga',
    'Mexico',
    'Mérida',
    'Murcia',
    'Ottawa',
    'Oviedo',
    'Ourense',
    'Pamplona',
    'Palma',
    'Palencia',
    'Pontevedra',
    'Rothenburg',
    'Rugen Island',
    'Santa María de Gracia',
    'San Francisco',
    'Santa Cruz de Tenerife',
    'Salamanca',
    'Santander',
    'Santiago de Compostela',
    'Sevilla',
    'Segovia',
    'Soria',
    'Tarragona',
    'Teruel',
    'Tokyo',
    'Toronto',
    'Toledo',
    'Quebec',
    'Vigo',
    'Valencia',
    'Valladolid',
    'Vitoria-Gasteiz',
    'Zaragoza',
    'Zuazo de Vitoria',
    'Zamora',
  ];

  
}
